'use client'
import { useState, useEffect, useCallback } from 'react'
import { Send, Check, Lock, Printer, ChevronDown, ChevronUp } from 'lucide-react'
import { Button, Card, CardContent, CardHeader, FormField, Input, Select, PageHeader, Badge } from '@/components/ui'
import { formatDate } from '@/lib/utils'

const SHIPPING_TYPES = [
  { value: 'letter', label: '✉️ Letter' },
  { value: 'package', label: '📦 Package' },
  { value: 'inpost', label: '🏪 InPost' },
  { value: 'vinted_go', label: '🛍️ Vinted Go' },
  { value: 'vinted', label: '🛍️ Vinted' },
]
const STATUS_LABELS: Record<string,string> = {
  unpacked:'To Pack', sorting:'Sorting', packing:'Packing', sent:'Sent ✓'
}
const STATUS_COLORS: Record<string,string> = {
  unpacked:'bg-secondary text-muted-foreground border border-border',
  sorting:'bg-sky-50 text-sky-700 border border-sky-200',
  packing:'bg-amber-50 text-amber-700 border border-amber-200',
  sent:'bg-emerald-50 text-emerald-700 border border-emerald-200',
}

export default function JoinerShippingPage() {
  const [existing, setExisting] = useState<any[]>([])
  const [formOpen, setFormOpen] = useState(true)
  const [loading, setLoading] = useState(true)
  const [showForm, setShowForm] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const [saving, setSaving] = useState(false)
  const [form, setForm] = useState({ shipping_type: '', address: '', email: '', phone: '', notes: '' })

  const fetchData = useCallback(async () => {
    const [d, openRes, dlRes] = await Promise.all([
      fetch('/api/sending-out').then(r => r.json()),
      fetch('/api/settings?key=sending_form_open').then(r => r.json()).catch(() => ({ value: 'true' })),
      fetch('/api/settings?key=sending_form_deadline').then(r => r.json()).catch(() => ({ value: '' })),
    ])
    setExisting(Array.isArray(d) ? d : [])
    const deadlinePassed = dlRes.value && new Date(dlRes.value) < new Date()
    setFormOpen(!deadlinePassed && openRes.value !== 'false')
    setLoading(false)
  }, [])

  useEffect(() => { fetchData() }, [fetchData])

  async function handleSubmit() {
    if (!form.shipping_type || !form.address) return
    setSaving(true)
    await fetch('/api/sending-out', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ ...form, joiner_submitted: true, status: 'unpacked' }),
    })
    setSubmitted(true)
    setShowForm(false)
    await fetchData()
    setSaving(false)
  }

  function handlePrint() {
    const content = `
      <html><head><title>Shipping Label</title>
      <style>
        body { font-family: Georgia, serif; padding: 40px; max-width: 500px; margin: 0 auto; }
        h1 { font-size: 18px; border-bottom: 2px solid #000; padding-bottom: 8px; margin-bottom: 20px; }
        .field { margin: 12px 0; }
        .label { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #888; }
        .value { font-size: 14px; font-weight: bold; margin-top: 3px; }
        .box { border: 1px solid #e0e0e0; padding: 20px; border-radius: 8px; margin: 16px 0; }
        .footer { margin-top: 28px; font-size: 10px; color: #aaa; text-align: center; border-top: 1px solid #eee; padding-top: 12px; }
      </style></head><body>
      <h1>✦ Giantz GO — Shipping Form</h1>
      <div class="box">
        <div class="field"><div class="label">Shipping Type</div><div class="value">${SHIPPING_TYPES.find(t=>t.value===form.shipping_type)?.label||form.shipping_type}</div></div>
        <div class="field"><div class="label">Delivery Address</div><div class="value" style="white-space:pre-wrap">${form.address}</div></div>
        ${form.email ? `<div class="field"><div class="label">Email</div><div class="value">${form.email}</div></div>` : ''}
        ${form.phone ? `<div class="field"><div class="label">Phone</div><div class="value">${form.phone}</div></div>` : ''}
        ${form.notes ? `<div class="field"><div class="label">Notes</div><div class="value">${form.notes}</div></div>` : ''}
      </div>
      <div class="footer">Generated by Giantz GO · ${new Date().toLocaleDateString()}</div>
      </body></html>`
    const w = window.open('', '_blank')
    if (w) { w.document.write(content); w.document.close(); w.print() }
  }

  return (
    <div className="flex flex-col h-full">
      <PageHeader title="Shipping" subtitle="Submit your shipping preferences" />
      <div className="flex-1 overflow-auto p-4 sm:p-6 space-y-5">

        {/* Form section */}
        {!loading && (
          !formOpen ? (
            <Card>
              <CardContent className="py-8 text-center">
                <Lock size={28} className="mx-auto mb-3 text-muted-foreground/40" />
                <p className="font-semibold text-sm">Shipping form is closed</p>
                <p className="text-xs text-muted-foreground mt-1">Your GOM hasn't opened the form yet.</p>
              </CardContent>
            </Card>
          ) : submitted ? (
            <div className="flex items-center gap-3 bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800 rounded-2xl px-5 py-4 text-emerald-700 dark:text-emerald-300">
              <Check size={18} />
              <div className="flex-1">
                <p className="font-semibold text-sm">Info submitted!</p>
                <p className="text-xs mt-0.5">Your GOM has received your shipping info.</p>
              </div>
              <Button variant="outline" size="sm" onClick={handlePrint}><Printer size={13}/> Print label</Button>
            </div>
          ) : (
            <div className="space-y-3">
              {/* Toggle button */}
              <button
                onClick={() => setShowForm(f => !f)}
                className="w-full flex items-center justify-between px-5 py-4 bg-card border border-border rounded-2xl hover:border-primary/30 hover:bg-primary/[0.02] transition-all group"
              >
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-primary/10 flex items-center justify-center">
                    <Send size={15} className="text-primary" />
                  </div>
                  <div className="text-left">
                    <p className="font-semibold text-sm">Submit Shipping Info</p>
                    <p className="text-xs text-muted-foreground">Fill in your address and shipping preferences</p>
                  </div>
                </div>
                {showForm ? <ChevronUp size={16} className="text-muted-foreground" /> : <ChevronDown size={16} className="text-muted-foreground" />}
              </button>

              {/* Collapsible form */}
              {showForm && (
                <Card>
                  <CardContent className="space-y-4 pt-5">
                    <FormField label="Shipping Type" required>
                      <Select options={SHIPPING_TYPES} placeholder="How should we ship it?" value={form.shipping_type} onChange={e=>setForm(f=>({...f,shipping_type:e.target.value}))} />
                    </FormField>
                    <FormField label="Shipping Address" required>
                      <textarea className="w-full px-3.5 py-2.5 rounded-xl border border-input bg-background text-sm resize-none focus:outline-none focus:ring-2 focus:ring-primary/25" rows={3} placeholder="Full name, street, city, postcode, country" value={form.address} onChange={e=>setForm(f=>({...f,address:e.target.value}))} />
                    </FormField>
                    <div className="grid grid-cols-2 gap-3">
                      <FormField label="Email"><Input type="email" placeholder="your@email.com" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/></FormField>
                      <FormField label="Phone"><Input type="tel" placeholder="+33 6 00 00 00 00" value={form.phone} onChange={e=>setForm(f=>({...f,phone:e.target.value}))}/></FormField>
                    </div>
                    <FormField label="Notes"><Input placeholder="Any special instructions…" value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></FormField>
                    <div className="flex gap-3">
                      <Button onClick={handleSubmit} disabled={saving||!form.shipping_type||!form.address} className="flex-1">
                        {saving ? 'Submitting…' : <><Send size={14}/> Submit</>}
                      </Button>
                      {form.address && form.shipping_type && (
                        <Button variant="outline" onClick={handlePrint}><Printer size={14}/> Preview</Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              )}
            </div>
          )
        )}

        {/* Packages */}
        <div>
          <p className="text-xs font-bold text-muted-foreground uppercase tracking-widest mb-3">Your Packages</p>
          {existing.length === 0
            ? <p className="text-sm text-muted-foreground text-center py-6">No packages yet.</p>
            : existing.map(e => (
              <Card key={e.id}>
                <CardContent className="py-4">
                  <div className="flex items-start justify-between gap-3">
                    <div>
                      <p className="font-semibold text-sm">{e.order?.shop?.name || 'Package'}</p>
                      {e.shipping_type && <p className="text-xs text-muted-foreground capitalize mt-0.5">{SHIPPING_TYPES.find(t=>t.value===e.shipping_type)?.label||e.shipping_type}</p>}
                      {e.shipping_deadline && <p className="text-xs text-muted-foreground mt-0.5">Pay by {formatDate(e.shipping_deadline)}</p>}
                    </div>
                    <Badge className={`${STATUS_COLORS[e.status]||STATUS_COLORS.unpacked} flex-shrink-0`}>
                      {STATUS_LABELS[e.status]||e.status}
                    </Badge>
                  </div>
                </CardContent>
              </Card>
            ))
          }
        </div>
      </div>
    </div>
  )
}
